### ISSUE TITLE
Failed to touch key error

### ISSUE THREAD

**Issue by tomasAlabes** [facebook/mcrouter#356]
Hi, I'm getting this error using 2 client libraries with mcrouter. This seems to happen when executing the command for the 1st time, then it works (until the entry is evicted). I'm using a `PrefixSelectorRoute` policy.

```
io.sixhours.memcached.cache.MemcachedOperationException: Failed to touch key
at io.sixhours.memcached.cache.XMemcachedClient.touch(XMemcachedClient.java:74)
at io.sixhours.memcached.cache.MemcachedCache.put(MemcachedCache.java:109)
[...]
Caused by: net.rubyeye.xmemcached.exception.MemcachedServerException: unexpected result mc_res_unknown (0) for touch, key=my_prefix#:something:namespace
at net.rubyeye.xmemcached.command.Command.decodeError(Command.java:259)
at net.rubyeye.xmemcached.command.Command.decodeError(Command.java:274)
at net.rubyeye.xmemcached.command.text.TextTouchCommand.decode(TextTouchCommand.java:76)
at net.rubyeye.xmemcached.codec.MemcachedDecoder.decode0(MemcachedDecoder.java:55)
at net.rubyeye.xmemcached.codec.MemcachedDecoder.decode(MemcachedDecoder.java:50)
at com.google.code.yanf4j.nio.impl.NioTCPSession.decode(NioTCPSession.java:281)
at com.google.code.yanf4j.nio.impl.NioTCPSession.decodeAndDispatch(NioTCPSession.java:223)
at com.google.code.yanf4j.nio.impl.NioTCPSession.readFromBuffer(NioTCPSession.java:194)
at com.google.code.yanf4j.nio.impl.AbstractNioSession.onRead(AbstractNioSession.java:184)
at com.google.code.yanf4j.nio.impl.AbstractNioSession.onEvent(AbstractNioSession.java:324)
at com.google.code.yanf4j.nio.impl.SocketChannelController.dispatchReadEvent(SocketChannelController.java:54)
at com.google.code.yanf4j.nio.impl.NioController.onRead(NioController.java:150)
at com.google.code.yanf4j.nio.impl.Reactor.dispatchEvent(Reactor.java:310)
at com.google.code.yanf4j.nio.impl.Reactor.run(Reactor.java:177)
```

The config is:

```
 "pools": {
    "MyPool": {
      "servers": [...]
    }
  },
 "route": {
    "type": "PrefixSelectorRoute",
    "policies": {
      "my_prefix": {
        "type": "OperationSelectorRoute",
        "operation_policies": {
          "add": "AllSyncRoute|Pool|MyPool",
          "delete": "AllSyncRoute|Pool|MyPool",
          "get": {
            "type": "MissFailoverRoute",
            "return_best_on_error": true,
            "children": [{
              "type": "PoolRoute",
              "pool": "MyPool"
            }]
          },
          "set": "AllSyncRoute|Pool|MyPool",
          "incr": "AllSyncRoute|Pool|MyPool",
          "decr": "AllSyncRoute|Pool|MyPool"
        }
      }
```

Is there a miss-configuration? 

`xmemcached` version `2.4.6`.
`spymemcached` version `1.1.1`.
`mcrouter` version `38.0.0`.

**Comment by tomasAlabes** [comment]
command was not supported and no default policy was set. Closing this issue.
